// 1. Write a multithreaded program that generates the Fibonacci series. The program 
// should work as follows: The user will enter on the command line the number of 
// Fibonacci numbers that the program is to generate. The program then will create a 
// separate thread that will generate the Fibonacci numbers, placing the sequence in 
// data that is shared by the threads (an array is probably the most convenient data 
// structure). When the thread finishes execution the parent will output the sequence 
// generated by the child thread. Because the parent thread cannot begin outputting the 
// Fibonacci sequence until the child thread finishes, this will require having the parent 
// thread wait for the child thread to finish.
#include<stdio.h>
#include<stdlib.h>
#include<pthread.h>
void* generate_fibonacci(void* param){
	int* arr=(int*)param;
	int n=arr[0];
	arr[1]=0;
	arr[2]=1;
	for(int i=3;i<=n;i++){
		arr[i]=arr[i-1]+arr[i-2];
	}
	return NULL;
}

int main(int argc, char const *argv[]){
	int n;
	printf("Enter number of fibonacci numbers:\n");
	scanf("%d",&n);
	int* arr=(int*)malloc((n+1)*sizeof(int));
	arr[0]=n;
	pthread_t thread;
	pthread_create(&thread,0,&generate_fibonacci,(void*)arr);
	pthread_join(thread,0);
	for(int i=1;i<=n;i++){
		printf("%d \t",arr[i]);
	}
	printf("\n");
	return 0;
}

// 2. Write a multithreaded program that calculates the summation of non-negative 
// integers in a separate thread and passes the result to the main thread.
#include<stdio.h>
#include<stdlib.h>
#include<pthread.h>
void* summation(void* param){
	int* arr=(int*)param;
	int sum=0;
	int n=arr[0];
	for(int i=1;i<=n;i++){
		if(arr[i]>0){
			sum+=arr[i];
		}
	}
	return (void*)sum;
}

int main(int argc,char const *argv[]){
	int n;
	printf("Enter the number of numbers:\n");
	scanf("%d",&n);
	int* arr=(int*)malloc((n+1)*sizeof(int));
	arr[0]=n;
	printf("Enter the numbers:\n");
	for(int i=1;i<=n;i++){
		scanf("%d",&arr[i]);
	}
	int answer=0;
	pthread_t thread;
	pthread_create(&thread,0,&summation,(void*)arr);
	pthread_join(thread,(void**)&answer);
	printf("Summation of non-negative numbers:%d\n",answer);
	return 0;
}

// 3. Write a multithreaded program for generating prime numbers from a given starting 
// number to the given ending number.
#include <stdlib.h>
#include <stdio.h>
#include <pthread.h>
#include <string.h>
void *prime(int *arr)
{
    int n1 = arr[1];
    int n2 = arr[2];
    printf("The Prime Numbers between '%d' and '%d' are: \n", n1, n2);
    for (int i = n1; i <= n2; i++)
    {
        int flag = 0;
        for (int j = 2; j <= i / 2; j++)
        {
            if ((i % j) == 0)
            {
                flag = 1;
                break;
            }
        }
        if (!flag)
            printf("%d ", i);
    }
    printf("\n");
}
int main()
{
    int arr[2];
    printf("Enter the Lower Limit: \n");
    scanf("%d", &arr[1]);
    printf("Enter the Upper Limit: \n");
    scanf("%d", &arr[2]);
    pthread_t thread;
    pthread_create(&thread, 0, &prime, (void *)arr);
    pthread_join(thread, NULL);
}

// 4. Write a multithreaded program that performs the sum of even numbers and odd 
// numbers in an input array. Create a separate thread to perform the sum of even 
// numbers and odd numbers. The parent thread has to wait until both the threads are 
// done.


#include<stdio.h>
#include<stdlib.h>
#include<pthread.h>

void* add_odd(void* args){
    int *arr = (int*)args;
    int n = arr[0];
    int *res = (int*)malloc(sizeof(int));
    *res = 0;
    for(int i=1;i<=n;i++){
        if(arr[i] %2== 1)
            *res += arr[i];
    }
    return (void*)res;
}

void* add_even(void* args){
    int *arr = (int*)args;
    int n = arr[0];
    int *res = (int*)malloc(sizeof(int));
    *res = 0;
    for(int i=1;i<=n;i++){
        if((arr[i] %2==0))
            *res += arr[i];
    }
    return (void*)res;
}

int main(int argc, char* argv[]){
    if(argc < 2){
        printf("Not enough arguments!\n");
        exit(EXIT_FAILURE);
    }
    int n = argc - 1;
    int* arr = (int*)calloc(n+1, sizeof(int)), *resEven, *resOdd;
    arr[0] = n;
    for(int i=0;i<n;i++){
        arr[i+1] = atoi(argv[i+1]);
    }
    pthread_t threadOdd, threadEven;
    pthread_create(&threadOdd, 0, &add_odd, (void*)arr);
    pthread_create(&threadEven, 0, &add_even, (void*)arr);
    pthread_join(threadOdd, (void**)&resOdd);
    pthread_join(threadEven, (void**)&resEven);
    printf("The Sum of Odd numbers is: %d\n", *resOdd);
    printf("The Sum of Even numbers is: %d\n", *resEven);
    return 0;
}
